interface=ens37
bind-interfaces

domain=starfleet.lan
local=/starfleet.lan/
expand-hosts
domain-needed
bogus-priv
no-resolv
server=9.9.9.9
server=1.1.1.1

host-record=enterprise.starfleet.lan,192.168.17.1
cname=www7.starfleet.lan,enterprise.starfleet.lan
cname=www8.starfleet.lan,enterprise.starfleet.lan
cname=php.starfleet.lan,enterprise.starfleet.lan
cname=admin.starfleet.lan,enterprise.starfleet.lan
cname=vscore.starfleet.lan,enterprise.starfleet.lan
cname=ftp.starfleet.lan,enterprise.starfleet.lan
cname=ldap.starfleet.lan,enterprise.starfleet.lan

dhcp-authoritative
dhcp-range=192.168.17.100,192.168.17.200,255.255.255.0,12h
dhcp-option=option:router,192.168.17.1
dhcp-option=option:dns-server,192.168.17.1
dhcp-option=option:domain-name,starfleet.lan

log-dhcp
log-facility=/var/log/dnsmasq.log
